remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: SolarCalculet
description: Documentation de l'outil de traitement des données ENEDIS

github:
  is_project_page: true
  repository_url: https://github.com/rhinosys/SolarCalculet
  owner_url: https://github.com/rhinosys

show_downloads: true
google_analytics: false
