name: Process ENEDIS Data

on:
  workflow_dispatch:
    inputs:
      file_source:
        description: 'Source du fichier CSV (URL HTTP ou chemin dans le dépôt)'
        required: true
        type: string
      source_type:
        description: 'Type de source (http ou repo)'
        required: true
        type: choice
        options:
          - http
          - repo
        default: 'repo'

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download file if HTTP
      if: inputs.source_type == 'http'
      run: |
        mkdir -p data
        curl -L "${{ github.event.inputs.file_source }}" -o data/input.csv

    - name: Copy file if from repo
      if: inputs.source_type == 'repo'
      run: |
        mkdir -p data
        cp "${{ github.event.inputs.file_source }}" data/input.csv

    - name: Process data
      run: |
        python -m solarcalculet data/input.csv

    - name: Upload XLSX files
      uses: actions/upload-artifact@v4
      with:
        name: processed-data
        path: |
          2023.xlsx
          2024.xlsx
        if-no-files-found: error
